type HtmlEventAttributes =
  | "onabort"
  | "onafterprint"
  | "onauxclick"
  | "onbeforeinput"
  | "onbeforematch"
  | "onbeforeprint"
  | "onbeforetoggle"
  | "onbeforeunload"
  | "onblur"
  | "oncancel"
  | "oncanplay"
  | "oncanplaythrough"
  | "onchange"
  | "onclick"
  | "onclose"
  | "oncommand"
  | "oncontextlost"
  | "oncontextmenu"
  | "oncontextrestored"
  | "oncopy"
  | "oncuechange"
  | "oncut"
  | "ondblclick"
  | "ondrag"
  | "ondragend"
  | "ondragenter"
  | "ondragleave"
  | "ondragover"
  | "ondragstart"
  | "ondrop"
  | "ondurationchange"
  | "onemptied"
  | "onended"
  | "onerror"
  | "onfocus"
  | "onformdata"
  | "onhashchange"
  | "oninput"
  | "oninvalid"
  | "onkeydown"
  | "onkeypress"
  | "onkeyup"
  | "onlanguagechange"
  | "onload"
  | "onloadeddata"
  | "onloadedmetadata"
  | "onloadstart"
  | "onmessage"
  | "onmessageerror"
  | "onmousedown"
  | "onmouseenter"
  | "onmouseleave"
  | "onmousemove"
  | "onmouseout"
  | "onmouseover"
  | "onmouseup"
  | "onoffline"
  | "ononline"
  | "onpagehide"
  | "onpagereveal"
  | "onpageshow"
  | "onpageswap"
  | "onpaste"
  | "onpause"
  | "onplay"
  | "onplaying"
  | "onpopstate"
  | "onprogress"
  | "onratechange"
  | "onrejectionhandled"
  | "onreset"
  | "onresize"
  | "onscroll"
  | "onscrollend"
  | "onsecuritypolicyviolation"
  | "onseeked"
  | "onseeking"
  | "onselect"
  | "onslotchange"
  | "onstalled"
  | "onstorage"
  | "onsubmit"
  | "onsuspend"
  | "ontimeupdate"
  | "ontoggle"
  | "onunhandledrejection"
  | "onunload"
  | "onvolumechange"
  | "onwaiting"
  | "onwheel";

/**
List of HTML event handler attributes.

@example
```
import htmlEventAttributes from "@prettier/html-event-attributes";

console.log(htmlEventAttributes);
//=> ['onabort', 'onafterprint', 'onauxclick', …]
```
*/
declare const htmlEventAttributes: readonly HtmlEventAttributes[];

export default htmlEventAttributes;
